### Gett
GET http://localhost:8090/api/lists/1/items/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIxODAyNDQsImlhdCI6MTc0MjEzNzA0NCwidXNlcl9pZCI6MTB9.lfHHvkqw2bPLAglWZZftQfJKorz5_xpbd_3rc2fHzW4