GET http://localhost:8090/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3NzQ2NTYsImlhdCI6MTc0NDczMTQ1NiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJpbGl5YTIyIn0.Sd367mNwuFJzqiF_WMnLOhJAU08FbyCrbBosD22L3mw