###SEND RESET REQUEST
POST http://localhost:8090/auth/reset-request
Content-Type: application/json

{
  "login": "qwertyy"
}

###REQUEST CONFIRM
POST http://localhost:8090/auth/reset-confirm
Content-Type: application/json

{
  "username": "qwertyy",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3NzgwNDYsImlhdCI6MTc0NDczNDg0NiwidXNlcm5hbWUiOiJxd2VydHl5In0.DGWUrS7USg-8ohBguYsCgVrY_A8VTK9n8jHs7kf0sms",
  "old_password": "qwerty",
  "new_password": "qwerty1"
}