POST http://localhost:8090/auth/sign-up
Content-Type: application/json

{
  "name": "iliya",
  "username": "bkmz1111",
  "password": "qwerty"
}

### Sign-In
POST http://localhost:8090/auth/sign-in
Content-Type: application/json

{
  "username": "bkmz1111",
  "password": "qwerty"
}

### Gett
GET http://localhost:8090/api/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzg0Nzk3NjcsImlhdCI6MTczODQzNjU2NywidXNlcl9pZCI6Nn0.5vmL8eOjQqmwDHwO7hEhgyfB1wN0NMoURQ1qodSLuWo
